In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from google.colab import files
uploaded = files.upload()

In [ ]:
df = pd.read_csv('vgames2.csv')

In [ ]:
df.isnull().sum()

In [ ]:
cdf = df.dropna()
cdf.isnull().sum()
cdf = cdf.fillna(0)

In [ ]:
cdf.duplicated().sum()

In [ ]:
cdf = cdf.drop(['Unnamed: 0'],axis=1)

In [ ]:
cdf = cdf.dropna(subset=['Year'])
cdf['Year'] = cdf['Year'].astype(int)

In [ ]:
cdf.loc[cdf['Year'] == 0, 'Year'] = 2000
cdf.loc[cdf['Year'] == 1, 'Year'] = 2001
cdf.loc[cdf['Year'] == 2, 'Year'] = 2002
cdf.loc[cdf['Year'] == 3, 'Year'] = 2003
cdf.loc[cdf['Year'] == 4, 'Year'] = 2004
cdf.loc[cdf['Year'] == 5, 'Year'] = 2005
cdf.loc[cdf['Year'] == 6, 'Year'] = 2006
cdf.loc[cdf['Year'] == 7, 'Year'] = 2007
cdf.loc[cdf['Year'] == 8, 'Year'] = 2008
cdf.loc[cdf['Year'] == 9, 'Year'] = 2009
cdf.loc[cdf['Year'] == 10, 'Year'] = 2010
cdf.loc[cdf['Year'] == 11, 'Year'] = 2011
cdf.loc[cdf['Year'] == 12, 'Year'] = 2012
cdf.loc[cdf['Year'] == 13, 'Year'] = 2013
cdf.loc[cdf['Year'] == 14, 'Year'] = 2014
cdf.loc[cdf['Year'] == 15, 'Year'] = 2015
cdf.loc[cdf['Year'] == 16, 'Year'] = 2016
cdf.loc[cdf['Year'] == 94, 'Year'] = 1994
cdf.loc[cdf['Year'] == 95, 'Year'] = 1995
cdf.loc[cdf['Year'] == 96, 'Year'] = 1996
cdf.loc[cdf['Year'] == 97, 'Year'] = 1997
cdf.loc[cdf['Year'] == 98, 'Year'] = 1998

In [ ]:
cdf.loc[cdf['Year'] == 86, 'Year'] = 1986

In [ ]:
year = cdf.query('Year < 1400')
year.sort_values('Year')

In [ ]:
cdf['NA_Sales'].value_counts()

In [ ]:
cdf["NA_Sales"].str.contains("M").sum()

In [ ]:
def convert_sales(sales):
    if "K" in sales:
        return float(sales.replace("K", "")) * 0.001
    elif "M" in sales:
        return float(sales.replace("M", ""))
    else:
        return float(sales)
        
cdf["NA_Sales"] = cdf["NA_Sales"].apply(convert_sales)

In [ ]:
cdf["EU_Sales"] = cdf["EU_Sales"].apply(convert_sales)

In [ ]:
cdf["JP_Sales"] = cdf["JP_Sales"].apply(convert_sales)

In [ ]:
cdf["Other_Sales"] = cdf["Other_Sales"].apply(convert_sales)

In [ ]:
cdf["Other_Sales"]

In [ ]:
result = cdf.groupby('Genre', as_index=False)['NA_Sales'].mean()
result = result.sort_values('NA_Sales', ascending=False)

In [ ]:
result2 = cdf.groupby('Genre', as_index=False)['EU_Sales'].mean()
result2 = result2.sort_values('EU_Sales', ascending=False)

In [ ]:
result3 = cdf.groupby('Genre', as_index=False)['JP_Sales'].mean()
result3 = result3.sort_values('JP_Sales', ascending=False)

In [ ]:
result4 = cdf.groupby('Genre', as_index=False)['Other_Sales'].mean()
result4 = result4.sort_values('Other_Sales', ascending=False)

In [ ]:
NAR = result
NAR

In [ ]:
EUR = result2
EUR

In [ ]:
JPR = result3 
JPR

In [ ]:
OTR =result4
OTR

In [ ]:
cdf['Total_Sales'] = cdf['NA_Sales'] + cdf['EU_Sales'] + cdf['JP_Sales'] + cdf['Other_Sales']
cdf

In [ ]:
cdf.sort_values('Year', ascending=False)

In [ ]:
cdf1 = cdf.drop(6906)

In [ ]:
cdf1.sort_values('Year', ascending=False)

In [ ]:
cdf1_year_top3_genre = cdf1.groupby([cdf1['Year']//5*5, 'Genre'])['Total_Sales'].sum().groupby(level=0, group_keys=False).nlargest(3)
cdf1_year_top3_genre = cdf1_year_top3_genre.reset_index()

In [ ]:
cdf1_year_top3_genre

5년단위로 그룹화를 하여서 가장많은 판매량을 가진 3개의 장르를 분석하였을때 

가장많은 판매량을 가진 장르가 계속해서 바뀌어왔기때문이다

인기량이란 그게임이 출시된 모든 플랫폼의 총합 판매량이라고 생각한다
그이유는 인기가있는 게임의 경우 한게임을 여러 플랫폼에서 구매하는 경우도 있고,
인기있는 게임은 말그대로 많은사람이 선호하는 게임이기때문이다.

In [ ]:
cdf = cdf.sort_values('Total_Sales', ascending=False)
cdf

인기가있는게임으로는 토탈판매량 기준 top3 인 

1.Wii Sports

2.Super Mario Bros.	
3.Mario Kart Wii		
3게임 다양한 연령층이 즐길수있는 대중성과,여러사람이 같이즐길수있는 멀티플레이의 재미 다양한 컨텐츠가 존재하는 게임이다.또한 조작이 간편하여
초심자도 같이 즐길수있는 장점이있다.

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.suptitle('Total Sales by Genre (Top 3) in 5-year period')

colors = ['#ff9999', '#66b3ff', '#99ff99']

min_year = cdf1_year_top3_genre['Year'].min()
max_year = cdf1_year_top3_genre['Year'].max()

num_subplots = (max_year - min_year) // 5 + 1

for i, year in enumerate(sorted(cdf1_year_top3_genre['Year'].unique())):
    df = cdf1_year_top3_genre[cdf1_year_top3_genre['Year'] == year]
    ax = plt.subplot(2, num_subplots, i+1)
    ax.pie(df['Total_Sales'], labels=df['Genre'], colors=colors, autopct='%.1f%%', startangle=90)
    ax.axis('equal')
    ax.set_title(f'{year}s')

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(16, 8))
plt.suptitle('Total Sales by Genre (Top 3) in 5-year period', fontsize=18)

colors = ['#ff9999', '#66b3ff', '#99ff99']

min_year = cdf1_year_top3_genre['Year'].min()
max_year = cdf1_year_top3_genre['Year'].max()

num_subplots = (max_year - min_year) // 5 + 1

for i, year in enumerate(sorted(cdf1_year_top3_genre['Year'].unique())):
    df = cdf1_year_top3_genre[cdf1_year_top3_genre['Year'] == year]
    ax = plt.subplot(2, num_subplots, i+1)
    ax.pie(df['Total_Sales'], labels=df['Genre'], colors=colors, autopct='%.1f%%', startangle=90, textprops={'fontsize': 10})
    ax.axis('equal')
    ax.set_title(f'{year}s', fontsize=14)

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(16, 8))
plt.suptitle('Total Sales by Genre (Top 3) in 5-year period', fontsize=18)

colors = ['#ff9999', '#66b3ff', '#99ff99']

min_year = cdf1_year_top3_genre['Year'].min()
max_year = cdf1_year_top3_genre['Year'].max()

num_subplots = (max_year - min_year) // 5 + 1

for i, year in enumerate(sorted(cdf1_year_top3_genre['Year'].unique())):
    df = cdf1_year_top3_genre[cdf1_year_top3_genre['Year'] == year]
    ax = plt.subplot(2, num_subplots, i+1)
    ax.pie(df['Total_Sales'], labels=df['Genre'], colors=colors, autopct='%.1f%%', startangle=90, 
           wedgeprops={'width': 0.5, 'edgecolor': 'white'}, pctdistance=0.8, textprops={'fontsize': 14})
    ax.axis('equal')
    ax.set_title(f'{year}s', fontsize=14)

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(16, 12))
plt.suptitle('Total Sales by Genre (Top 3) in 5-year period', fontsize=18)

colors = ['#ff9999', '#66b3ff', '#99ff99']

min_year = cdf1_year_top3_genre['Year'].min()
max_year = cdf1_year_top3_genre['Year'].max()

num_subplots = (max_year - min_year) // 5 + 1

for i, year in enumerate(sorted(cdf1_year_top3_genre['Year'].unique())):
    df = cdf1_year_top3_genre[cdf1_year_top3_genre['Year'] == year]
    ax = plt.subplot(4, num_subplots // 2, i+1)
    ax.pie(df['Total_Sales'], labels=df['Genre'], colors=colors, autopct='%.1f%%', startangle=90, textprops={'fontsize': 12})
    ax.axis('equal')
    ax.set_title(f'{year}s', fontsize=14)

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(16, 12))
plt.suptitle('Total Sales by Genre (Top 3) in 5-year period', fontsize=18)

colors = ['#ff9999', '#66b3ff', '#99ff99']

min_year = cdf1_year_top3_genre['Year'].min()
max_year = cdf1_year_top3_genre['Year'].max()

num_subplots = (max_year - min_year) // 5 + 1

for i, year in enumerate(sorted(cdf1_year_top3_genre['Year'].unique())):
    df = cdf1_year_top3_genre[cdf1_year_top3_genre['Year'] == year]
    ax = plt.subplot(4, num_subplots // 2, i+1)
    ax.pie(df['Total_Sales'], labels=df['Genre'], colors=colors, autopct='%.1fM%%', startangle=90, textprops={'fontsize': 12})
    ax.axis('equal')
    ax.set_title(f'{year}s', fontsize=14)

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

top10 = cdf.nlargest(10, 'Total_Sales')

plt.figure(figsize=(12,6))
plt.bar(top10['Name'], top10['Total_Sales'])
plt.title('Top 10 Games by Total Sales')
plt.xticks(rotation=90)
plt.xlabel('Name of the Game')
plt.ylabel('Total Sales (millions)')
plt.show()